version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: core_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: --------
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis_server
    ports:
      - "6379:6379"